version: 2.1.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\SerialPortRx.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: aGGrRJIt9TCAVTXYJIYyjgSqSucijjZvzm/Md7GnYkb0jd8SJ19rlM+QnI13EJws
