version: 1.4.{build}
image: Visual Studio 2019
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\SerialPortRx.*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: CIdiwHmj8amXRtjE0AwwlBSj55TGDg0yLqm/YthICWaUncKoJmYabpu2YqXIuOVd
