version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
platform: Any CPU
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: T8iCmiuaS2uvvWctYHGtxZkuhP5zPtpNYf27RivL2n9/qDb0O3/YevGed7qEwfmR